{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "18a37412_0c3cccea",
        "filename": "test/user_mgr_test.cpp",
        "patchSetId": 9
      },
      "lineNbr": 376,
      "author": {
        "id": 1000022
      },
      "writtenOn": "2022-11-08T07:07:15Z",
      "side": 1,
      "message": "Can you explain what is this Test? I am guessing below\n- There is already a user and you are trying to add user0 again?",
      "revId": "c152baeb84d64b392dfcd0f2cef7df7b408c11b2",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "36987fb5_feb524cd",
        "filename": "test/user_mgr_test.cpp",
        "patchSetId": 9
      },
      "lineNbr": 395,
      "author": {
        "id": 1000022
      },
      "writtenOn": "2022-11-08T07:07:15Z",
      "side": 1,
      "message": "Why I should expect a throw here? Where we are setting that IPMI max users?\nIs it 15 then there should be 15 user add commands and after that there should be an exception which I should expect.\nSeems I am missing something here.",
      "range": {
        "startLine": 394,
        "startChar": 1,
        "endLine": 395,
        "endChar": 18
      },
      "revId": "c152baeb84d64b392dfcd0f2cef7df7b408c11b2",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}